import "./globals.css";

export const metadata = {
  title: "CY Diablo Live",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <link rel="icon" href="/favicon.png" />

      <body className="bg-gradient-to-bl from-[#1b1a1a] to-[#151515] bg-center bg-fixed min-h-lvh"
      >
        {children}
      </body>
    </html >
  );
}
