import "./globals.css";

export const metadata = {
  title: "NextJS",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-[url('/layoutBG.png')] bg-center bg-fixed min-h-lvh">
        {children}
      </body>
    </html >
  );
}
