import "./globals.css";

export const metadata = {
  title: "CY Diablo Live",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <link rel="icon" href="/favicon.png" />

      <body className="bg-gradient-to-br from-[#2c2626] to-[#04040a] bg-center bg-fixed min-h-screen"
      >
        {children}
      </body>
    </html >
  );
}
